name: Generate GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Snake
        uses: Platane/snk@v1
        with:
          github_user: 'Rinaldo23'
          output_format: 'svg'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
