name: "Latest blog"
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-blogs:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in HashNode posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://rinaldo.hashnode.dev/"
